name: GodMode
main: blood\GodMode
version: 1.0.0
api: 4.0.0
author: BloodFistMCPE
description: Toggle immortality for yourself or others!

commands:
 god:
  description: "Toggle immortality!"
  permission: "godmode"
  
permissions:
  godmode:
    default: op