---
# This will alert a player that god mode has been enabled/disabled.
# For example, /god BloodFistMCPE will alert BloodFistMCPE.
alert-player: true

# If alert-player is set to true, these messages will be sent.
alert-enabled-message: "{player} has enabled gode mode for you."
alert-disabled-message: "{player} has disabled gode mode for you."

# These are the messages sent when /god is ran without args.
enabled-message: "God mode has been enabled."
disabled-message: "God mode has been disabled."

# This message will be sent if an invalid player is given.
invalid-player: "Player not online."

# This message will be sent if a player doesn't have permission.
invalid-permission: "You do not have permission to use this command."
...